### ISSUE TITLE
Potentially switch to Apex's UP

### ISSUE THREAD

**Issue by tomouchuu** [uchuuio/meta#4]
So with Up having a 50% forever discount it is $10 a month. $5 cheaper than Now with the added bonus that I wouldn't have to pay extra for team seats so we can just invite people as needed. Investigate this

https://up.docs.apex.sh/ 

https://github.com/apex/up

## TODO:
- [ ] Migrate uchuu.io to Up (Ideally do this first else, continue and do this at first opportunity)
- [ ] uchuu/Micro-Translate -- https://github.com/uchuuio/translate-server/issues/1
- [x] personal/me-api (not production) -- https://github.com/tomouchuu/me-api/issues/5
- [x] personal/personal
- [ ] uchuu/Dempach Archive -- https://github.com/uchuuio/dempach-archive/issues/9
- [x] uchuu/Start
- [x] uchuu/Zen
- [x] personal/tomOshi

### Extra
- [ ] Add to Readme what we use
- [ ] How to get added to the uchuuio team

**Comment by tomouchuu** [comment]
Been testing this with Start & Zen and it's been good. The only issue I have so far is that adding the `/staging` and `/production` urls will break my static sites until I migrate the uchuu domain to Up. Will do this first thing and then migrate over each site one by one.

I think our staging urls should be as a subdomain so we'd have something like `https://staging.translate.uchuu.io` for staging and production like `https://translate.uchuu.io`

Here is the order to follow:
- [ ] Migrate uchuu.io to Up (Ideally do this first else, continue and do this at first opportunity)
- [ ] uchuu/Micro-Translate
- [ ] personal/me-api
- [ ] personal/personal
- [ ] uchuu/Dempach Archive
- [ ] uchuu/Start
- [ ] uchuu/Zen
- [ ] personal/tomOshi

**Comment by tomouchuu** [comment]
So found some issues, main one is the staging urls are currently `stage-{app}.uchuu.io` this is because I'm unable to set a CAA or something on each subdomain but this is ok I guess.

Happy with it so far! Once I've potentially got the issues for micro-translate & dempach set up then I'll probably upgrade (especially since I just paid for now).

**Comment by tomouchuu** [comment]
Also will need to update the readme with using it and how to get added to the uchuuio team there:

- [ ] Add to Readme what we use
- [ ] How to get added to the uchuuio team

**Comment by tomouchuu** [comment]
Basically abandoning this, there are issues I can't sort and it's just easier with now as I already pay them and static sites are always free and such
